name: "Merge Base"
description: "Find Merge Base"

inputs:
  head-ref:
    description: |
      The head ref to compare
        e.g. `refs/heads/feature-branch`
    required: true
  base-ref:
    description: |
      The base ref to compare
        e.g. `refs/heads/main`
    required: true
  deepen:
    description: "Depth by which to deepen the fetch"
    required: false
    default: '128'
  max-deepen:
    description: "The maximum amount to deepen by before failing"
    required: false
    default: '65536'
  remote:
    description: |
      The remote to fetch from
    required: false
    default: "origin"

runs:
  using: "composite"
  steps:

    - name: Find base
      id: base
      shell: bash
      env:
        HEAD_REF: ${{ inputs.head-ref }}
        BASE_REF: ${{ inputs.base-ref }}
        REMOTE: ${{ inputs.remote }}
        DEEPEN: ${{ inputs.deepen }}
        MAX_DEEPEN: ${{ inputs.max-deepen }}
      run: |
        . '${{ github.action_path }}/base.sh'
        echo "sha=${MERGE_BASE}" >> $GITHUB_OUTPUT

outputs:
  sha:
    description: "The merge base of the head and base refs"
    value: ${{ steps.base.outputs.sha }}
