name: Create Pull Request
description: Create a pull request

inputs:
  remote:
    description: |
      The remote to push the branch to
    required: false
    default: "origin"
  base-branch:
    description: |
      The base branch to version against
    required: true
  pkg-name:
    description: |
      The package name being versioned
    required: true
  gh-token:
    description: |
      The GitHub token
    required: true

runs:
  using: composite
  steps:

    - name: Create Pull Request
      id: pr
      shell: bash
      env:
        GH_TOKEN: ${{ inputs.gh-token }}
        REMOTE: ${{ inputs.remote }}
        BASE_BRANCH: ${{ inputs.base-branch }}
        PKG_NAME: ${{ inputs.pkg-name }}
      run: |
        . '${{ github.action_path }}/pr.sh'
        echo "changes=${CHANGES}" >> $GITHUB_OUTPUT
        echo "url=${URL}" >> $GITHUB_OUTPUT

outputs:
  url:
    description: The URL of the created pull request
    value: ${{ steps.pr.outputs.url }}
  changes:
    description: Whether changes were made
    value: ${{ steps.pr.outputs.changes }}
