name: "Fetch refs"
description: "Fetch additional refs from a remote"

inputs:
  fetch-depth:
    description: "The depth of commits to fetch."
    required: false
    default: '1'
  ref-specs:
    description: |
      Additional ref specs to fetch
        e.g. `["refs/heads/another-branch:refs/remotes/origin/another-branch", "refs/heads/yet-another-branch:refs/remotes/origin/yet-another-branch"]`
      Should be a JSON array, where each element is a ref spec
      Each ref will be fetched with a depth of `fetch-depth`
      If the remote ref does not exist, the local ref will not be created
    required: true
  remote:
    description: |
      The remote to fetch additional refs from
    required: false
    default: "origin"

runs:
  using: "composite"
  steps:
    - name: Fetch
      shell: bash
      env:
        FETCH_DEPTH: ${{ inputs.fetch-depth }}
        RAW_REF_SPECS: ${{ inputs.ref-specs }}
        REMOTE: ${{ inputs.remote }}
      run: |
        '${{ github.action_path }}/fetch.sh'
