name: "CD NPM Package"
description: "Deploy NPM package"

inputs:
  semver-branch:
    description: |
      The branch to use for versioning
    required: true
  base-branch:
    description: |
      The base branch to version against
    required: true
  cwd:
    description: |
      The directory of the package to version
    required: true
  remote:
    description: |
      The remote to push the branch to
    required: false
    default: "origin"
  gh-token:
    description: |
      The GitHub token
    required: true

runs:
  using: "composite"
  steps:

    - name: Git
      uses: Duncan3142/mono/actions/git/setup@main

    - name: PNPM
      id: pnpm
      uses: Duncan3142/mono/actions/pnpm/setup@main
      with:
        cwd: ${{ inputs.cwd }}

    - name: Changesets
      id: changesets
      uses: Duncan3142/mono/actions/pnpm/changesets@main
      with:
        cwd: ${{ inputs.cwd }}

    - if: steps.changesets.outputs.count != '0'
      name: Version
      id: version
      uses: Duncan3142/mono/actions/version/npm@main
      with:
        semver-branch: ${{ inputs.semver-branch }}
        base-branch: ${{ inputs.base-branch }}
        cwd: ${{ inputs.cwd }}
        pkg-name: ${{ steps.pnpm.outputs.name }}
        gh-token: ${{ inputs.gh-token }}

    - if: steps.version.outcome == 'skipped'
      name: Publish
      uses: Duncan3142/mono/actions/publish/npm@main
      with:
        cwd: ${{ inputs.cwd }}
