name: "Version"
description: "Apply semantic versioning on the current branch"

inputs:
  base:
    description: |
      The base ref to version against, must exist locally
    required: true
  cwd:
    description: |
      The directory of the package to version
    required: true
  remote:
    description: |
      The remote to push the branch to
    required: false
    default: "origin"

runs:
  using: "composite"
  steps:

    - name: Version
      id: version
      shell: bash
      run: |
        VERSIONING_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
        echo "Resetting ${VERSIONING_BRANCH} to ${{ inputs.base }}"
        git reset --hard ${{ inputs.base }}

        pnpm exec changeset version

        git add .

        if git commit -m "Semver $(cat package.json | jq '.name')"; then
          git push --force-with-lease '${{ inputs.remote }}' "$(git rev-parse --abbrev-ref HEAD)"
          echo "changes=true" >> $GITHUB_OUTPUT
        else
          echo "changes=false" >> $GITHUB_OUTPUT
        fi
      working-directory: ${{ inputs.cwd }}

outputs:
  changes:
    description: "'true' if the package was versioned, 'false' otherwise"
    value: ${{ steps.version.outputs.changes }}
