name: "Changesets"
description: "Package changeset status"

inputs:
  cwd:
    description: |
      The directory of the package
    required: true

runs:
  using: "composite"
  steps:

    - name: Status
      id: status
      shell: bash
      run: |
        . '${{ github.action_path }}/status.sh'
        echo "count=${CHANGE_COUNT}" >> "$GITHUB_OUTPUT"
      working-directory: ${{ inputs.cwd }}

outputs:
  count:
    description: The number of pending changesets
    value: ${{ steps.status.outputs.count }}
