name: "Version NPM Package"
description: "Apply semantic versioning"

inputs:
  semver-branch:
    description: |
      The branch to use for versioning
    required: true
  base-branch:
    description: |
      The base branch to version against
    required: true
  pkg-name:
    description: |
      The package to version
    required: true
  cwd:
    description: |
      The directory of the package to version
    required: true
  remote:
    description: |
      The remote to push the branch to
    required: false
    default: "origin"
  gh-token:
    description: |
      The GitHub token
    required: true

runs:
  using: "composite"
  steps:

    - name: SemVer branch
      id: semver-branch
      uses: Duncan3142/mono/actions/git/semver-branch@main
      with:
        semver-branch: ${{ inputs.semver-branch }}
        base-branch: ${{ inputs.base-branch }}

    - name: Version
      id: version
      shell: bash
      run: |
        make version
      working-directory: ${{ inputs.cwd }}

    - name: PR
      id: pr
      uses: Duncan3142/mono/actions/github/pr@main
      with:
        remote: ${{ inputs.remote }}
        base-branch: ${{ inputs.base-branch }}
        pkg-name: ${{ inputs.pkg-name }}
        gh-token: ${{ inputs.gh-token }}

outputs:
  url:
    description: The PR URL
    value: ${{ steps.pr.output.url }}
  changes:
    description: Whether changes were made
    value: ${{ steps.pr.output.changes }}
