name: "Setup"
description: "Setup PNPM"
inputs:
  github-actor:
    description: "GitHub actor"
    required: true
  cwd:
    description: "Working directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: Working Directory
      shell: bash
      run: |
        echo Original directory: $(pwd)
        cd "$WORK_DIR"
        echo Current directory: $(pwd)
        echo MONO_WORK_DIR: "$MONO_WORK_DIR"
      env:
        WORK_DIR: ${{ inputs.cwd }}
    - name: Git Config
      shell: bash
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      env:
        GITHUB_ACTOR: ${{ inputs.github-actor }}
    - uses: pnpm/action-setup@v3
      with:
        version: latest
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        check-latest: true
        cache: "pnpm"
        node-version-file: ${{ inputs.cwd }}/.nvmrc
        cache-dependency-path: ${{ inputs.cwd }}/pnpm-lock.yaml
    - name: Install
      shell: bash
      run: |
        pnpm install --frozen-lockfile
