name: "Setup"
description: "Setup PNPM"
inputs:
  github-actor:
    description: "GitHub actor"
    required: true
  cwd:
    description: "Working directory"
    required: true

runs:
  using: "composite"
  steps:
    - name: Git Config
      shell: bash
      run: |
        git config --global user.name "$GITHUB_ACTOR"
        git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"
      env:
        GITHUB_ACTOR: ${{ inputs.github-actor }}
    - uses: pnpm/action-setup@v3
      with:
        version: latest
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        check-latest: true
        cache: "pnpm"
        node-version-file: .nvmrc
        cache-dependency-path: pnpm-lock.yaml
      working-directory: ${{ inputs.cwd }}
    - name: Install
      shell: bash
      run: |
        pnpm install --frozen-lockfile
      working-directory: ${{ inputs.cwd }}
