name: "Utility scripts"
description: "Install utility scripts"

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        exit 1
        ./setup.sh
      working-directory: ${{ github.action_path}}
