name: "Fetch Remote NPM Package Details"
description: "Fetch Remote NPM Package Details"

inputs:
  name:
    description: |
      The name of the package
    required: true
  version:
    description: |
      The version of the package
    required: false
    default: "latest"

runs:
  using: "composite"
  steps:

    - name: Check remote
      id: remote
      shell: bash
      env:
        NAME: ${{ inputs.name }}
        VERSION: ${{ inputs.version }}
      run: |
        EXISTS=false
        LATEST='0.0.0'
        if JSON=$(pnpm show "${NAME}@${VERSION}" --json); then
          EXISTS=true
          echo "Package ${NAME} already exists at version ${VERSION}"

          LATEST=$(echo -E "${JSON}" | jq -r '."dist-tags".latest')
          echo "Latest version is ${LATEST}"
        else
          echo "Package ${NAME} does not exist at version ${VERSION}"
        fi
        echo "exists=${EXISTS}" >> $GITHUB_OUTPUT
        echo "latest=${LATEST}" >> $GITHUB_OUTPUT

outputs:
  exists:
    description: The package version exists in the registry
    value: ${{ steps.remote.output.exists == 'true' }}
  latest:
    description: The latest version of the package
    value: ${{ steps.remote.output.latest }}
