name: "Setup"
description: "Setup Git"

inputs:
  fetch-depth:
    description: "The depth of commits to fetch."
    required: false
    default: '1'

runs:
  using: "composite"
  steps:

    - name: Clone
      uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: User
      shell: bash
      run: |
        '${{ github.action_path }}/user.sh'
