name: "Checkout SemVer Branch"
description: "Checkout SemVer Branch"

inputs:
  semver-branch:
    description: |
      The branch to use for versioning
    required: true
  base-branch:
    description: |
      The base branch to version against, must exist locally
    required: true

runs:
  using: "composite"
  steps:

    - name: Base check
      id: base-check
      shell: bash
      env:
        BASE_BRANCH: ${{ inputs.base-branch }}
      run: |
        '${{ github.action_path }}/base-check.sh'

    - name: Versioning Branch
      id: checkout
      uses: Duncan3142/mono/actions/git/checkout@main
      with:
        name: ${{ inputs.semver-branch }}
        create: true

    - name: Reset
      id: reset
      shell: bash
      env:
        BASE_BRANCH: ${{ inputs.base-branch }}
      run: |
        '${{ github.action_path }}/reset.sh'

outputs:
  sha:
    description: "The merge base of the head and base refs"
    value: ${{ steps.base.outputs.sha }}
