name: "Debug"
description: "Check script paths"

inputs:
  cwd:
    description: |
      The directory of the package
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup
      shell: bash
      run: |
        ./setup.sh
      working-directory: ${{ github.action_path}}
    - name: Debug
      shell: bash
      run: |
        mono-debug.js
      working-directory: ${{ inputs.cwd }}
