name: "Publish NPM Package"
description: "Publish NPM Package"

inputs:
  cwd:
    description: |
      The directory of the package
    required: true
  build:
    description: |
      The build command to run
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - if: inputs.build != ''
      name: Build
      id: build
      shell: bash
      run: |
        echo Running build command
        ${{ inputs.pre }}
      working-directory: ${{ inputs.cwd }}

    - name: Publish
      id: publish
      shell: bash
      run: |
        echo Running publish...
        # pnpm exec changeset publish
        # git push --follow-tags --no-verify
      working-directory: ${{ inputs.cwd }}
