name: "GitHub CLI Auth"
description: "GitHub CLI Auth"

inputs:
  token:
    description: "GitHub Token"
    required: true

runs:
  using: "composite"

  steps:
    - name: Login
      shell: bash
      run: |
        gh auth login --with-token <<< "${AUTH_TOKEN}"
        gh auth setup-git
      env:
        AUTH_TOKEN: ${{ inputs.token }}
