name: CD

on:
  push:
    branches:
      - main

permissions:
  packages: write
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: Duncan3142/js-pkgs/actions/setup@6d36836b307f579880e650e1cd6473cbe4a2772c
        with:
          github-actor: ${{ github.actor }}
      - name: Changesets
        id: changesets
        uses: ./actions/changesets
