name: CD

on:
  push:
    branches:
      - main

permissions:
  packages: write
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./.github/actions/setup
        with:
          github-actor: ${{ github.actor }}
      - name: Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          version: ./build/version.sh
          publish: ./build/publish.sh
          setupGitUser: false
          createGithubReleases: true
