name: CD

on:
  push:
    branches:
      - main

permissions:
  packages: write
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: Duncan3142/js-pkgs/actions/setup@b9ccf32ec9dc855d2392e0bf2fc240441209699d # @gha/setup@0.0.4
        with:
          github-actor: ${{ github.actor }}
      - name: Changesets
        id: changesets
        uses: Duncan3142/js-pkgs/actions/changesets@3abd7e8d1420e40ab9896e74d9cfe9119cb55f8c # @gha/changesets@0.0.2
