name: CD

on:
  push:
    branches:
      - main

permissions:
  packages: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_REPO_CONTENT }}
      - name: Setup
        uses: ./.github/actions/setup
        with:
          packages-token: ${{ secrets.GITHUB_TOKEN }}
          github-actor: ${{ github.actor }}
      - name: Changesets
        id: changesets
        uses: changesets/action@v1
        with:
          publish: ./build/publish.sh
          setupGitUser: false
          createGithubReleases: true
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_CONTENT }}
          GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
