name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]
    branches: main

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup
        uses: Duncan3142/js-pkgs/actions/setup@gha-setup%400.0.2
        with:
          github-actor: ${{ github.actor }}
      - name: Build
        uses: Duncan3142/js-pkgs/actions/build@main
        with:
          skip-changesets: ${{ github.event.pull_request.title == 'Version Packages' }}
