name: Debug

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/debug.yml'
      - 'actions/**'

permissions:
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  VERSIONING_BRANCH: ${{ vars.VERSIONING_BRANCH }}
  INITIAL_FETCH_DEPTH: 16

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Git
        uses: Duncan3142/mono/actions/git/setup@main
        with:
          fetch-depth: ${{ env.INITIAL_FETCH_DEPTH }}
          ref-specs: '["refs/heads/${{ env.VERSIONING_BRANCH }}:refs/remotes/origin/${{ env.VERSIONING_BRANCH }}"]'

      - name: Checkout Versioning Branch
        id: checkout
        uses: Duncan3142/mono/actions/git/checkout@main
        with:
          name: ${{ env.VERSIONING_BRANCH }}

      - name: Merge base
        id: base
        uses: Duncan3142/mono/actions/git/merge-base@main
        with:
          head-ref: refs/heads/${{ env.VERSIONING_BRANCH }}
          base-ref: ${{ github.ref}}

      - name: Version
        id: version
        run: |
          git rebase main

          CHANGES_TMP_DIR="${{ runner.temp }}/changesets"
          mkdir -p "${CHANGES_TMP_DIR}"
          echo "CHANGES_TMP_DIR=${CHANGES_TMP_DIR}" >> $GITHUB_ENV

          rm ./.changeset/*.md

          git status

          # git checkout main --

          # git push --force-with-lease origin ${{ env.VERSIONING_BRANCH }}
