name: Debug

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/debug.yml'
      - 'actions/**'

permissions:
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  VERSIONING_BRANCH: ${{ vars.VERSIONING_BRANCH }}
  INITIAL_FETCH_DEPTH: 16

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git
        uses: ./actions/git/setup
        with:
          fetch-depth: ${{ env.INITIAL_FETCH_DEPTH }}
          ref-specs: '["refs/heads/${{ env.VERSIONING_BRANCH }}:refs/remotes/origin/${{ env.VERSIONING_BRANCH }}"]'
      - name: Checkout Versioning Branch
        run: |
          gh --version

          echo GITHUB_REF is "${GITHUB_REF}"

          if git checkout "${VERSIONING_BRANCH}"; then
            echo "Branch ${VERSIONING_BRANCH} exists locally"
          else
            echo "Branch ${VERSIONING_BRANCH} does not exist locally"
            git checkout -b "${VERSIONING_BRANCH}" --track "origin/${VERSIONING_BRANCH}"
          fi
      - name: Merge base
        id: base
        uses: Duncan3142/mono/actions/git/merge-base@main
        with:
          head-ref: refs/heads/${{ env.VERSIONING_BRANCH }}
          base-ref: ${{ github.ref}}

    # ----------------------------------------------------- #

      # - name: Set Temp Directory
      #   run: |
      #     CHANGES_TMP_DIR="${{ runner.temp }}/changesets"
      #     mkdir -p "${CHANGES_TMP_DIR}"
      #     echo "CHANGES_TMP_DIR=${CHANGES_TMP_DIR}" >> $GITHUB_ENV

      # - name: Debug
      #   run: |
          # rm ./.changeset/*.md
          # git checkout main --
