name: Debug

on:
  push:

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Debug
    runs-on: ubuntu-latest
    steps:

      - name: Setup
        uses: Duncan3142/mono/actions/git/setup@main

      - name: Debug
        uses: Duncan3142/mono/actions/debug/@main
