name: Debug

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  VERSIONING_BRANCH: ${{ vars.VERSIONING_BRANCH }}


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git Tings
        run: |
          echo Versioning Branch: $VERSIONING_BRANCH
          echo "Remotes"
          git remote -v
          echo "Pre fetch"
          echo "Branches"
          git branch -a
          echo "Fetching Meow"
          git fetch --depth=1 origin 'refs/heads/Meow/*:refs/remotes/origin/Meow/*' || true
          echo "Meow Branches"
          git branch -a
          echo "Fetching CI"
          git fetch --depth=1 origin "refs/heads/${VERSIONING_BRANCH}:refs/remotes/origin/${VERSIONING_BRANCH}" || true
          echo "Ci Branches"
          git branch -a
