name: Debug

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  VERSIONING_BRANCH: ${{ vars.VERSIONING_BRANCH }}


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Git Tings
        run: |
          gh --version

          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

          echo "Fetching CI"
          git fetch origin "refs/heads/${VERSIONING_BRANCH}:refs/remotes/origin/${VERSIONING_BRANCH}" || true
          echo "Branch list"
          git branch -a
          git checkout "${VERSIONING_BRANCH}" || git checkout -b "{$VERSIONING_BRANCH}" --track "origin/${VERSIONING_BRANCH}"

          echo "Merge Base"
          git merge-base main $VERSIONING_BRANCH

          git merge main
