name: Debug

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/debug.yml'

permissions:
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  VERSIONING_BRANCH: ${{ vars.VERSIONING_BRANCH }}
  INITIAL_FETCH_DEPTH: 32

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: ${{ env.INITIAL_FETCH_DEPTH }}
      - name: Set Temp Directory
        run: |
          CHANGES_TMP_DIR="${{ runner.temp }}/changesets"
          mkdir -p "${CHANGES_TMP_DIR}"
          echo "CHANGES_TMP_DIR=${CHANGES_TMP_DIR}" >> $GITHUB_ENV
      - name: Git Tings
        run: |
          gh --version

          echo GITHUB_REF is "${GITHUB_REF}"

          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"

          echo "Fetching versioning branch"
          git fetch origin --depth="${INITIAL_FETCH_DEPTH}" "refs/heads/${VERSIONING_BRANCH}:refs/remotes/origin/${VERSIONING_BRANCH}" || true

          echo "Branch list"
          git branch -a

          git checkout "${VERSIONING_BRANCH}" || git checkout -b "${VERSIONING_BRANCH}" --track "origin/${VERSIONING_BRANCH}"

          FETCH_DEPTH="${INITIAL_FETCH_DEPTH}""
          MAX_DEPTH=65536

          echo "Finding merge base"
          until git merge-base main "${VERSIONING_BRANCH}" 1> "${CHANGES_TMP_DIR}/merge-base"
          do

            if [ $FETCH_DEPTH -gt $MAX_DEPTH ]; then
              echo "Fetch depth exceeded ${MAX_DEPTH}"
              exit 1
            fi

            echo "Deepening fetch..."
            FETCH_DEPTH=$((FETCH_DEPTH * 2))
            git fetch --deepen=${FETCH_DEPTH} origin "${GITHUB_REF}" "refs/heads/${VERSIONING_BRANCH}"
          done

          echo "Merge base found"
          cat "${CHANGES_TMP_DIR}/merge-base

          # ----------------------------------------------------- #

          # rm ./.changeset/*.md
          # git checkout main --
