name: Debug

on:
  push:
    paths:
     - '.github/workflows/debug.yml'
     - 'actions/cd/npm-container/**'

env:
  MONO_WORK_DIR: ${{ vars.PRETTIER_CONFIG_DIR }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Debug
    runs-on: ubuntu-latest
    steps:

      - name: Debug
        uses: Duncan3142/mono/actions/cd/npm-container@main
        env:
          LOG_LEVEL: 1
        with:
          cwd: ${{ env.MONO_WORK_DIR }}
