name: Debug

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git Tings
        run: |
          git remote -v
          git branch -a
