name: Debug

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/debug.yml'
      - 'actions/debug/**'

permissions:
  packages: read
  contents: read

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

env:
  MONO_WORK_DIR: ${{ vars.PRETTIER_CONFIG_DIR }}
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FORCE_COLOR: 3
  LBIN: /home/runner/.local/bin
  LLIB: /home/runner/.local/mono
  MONO_LOGS_ROOT: /tmp/mono/logs

jobs:
  test:
    name: Debug
    runs-on: ubuntu-22.04
    steps:

      - name: GIT
        uses: actions/checkout@v4

      - name: Debug
        run: |
          echo Config
          cat .git/config
          echo Token
          echo "x-access-token:${GITHUB_TOKEN}" | base64
