name: Debug

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  VERSIONING_BRANCH: ${{ vars.VERSIONING_BRANCH }}


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  debug:
    name: Debug
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Git Tings
        run: |
          gh -v


          echo "Fetching CI"
          git fetch --depth=1 origin "refs/heads/${VERSIONING_BRANCH}:refs/remotes/origin/${VERSIONING_BRANCH}" || true
          echo "CI Branches"
          git branch -a
          git checkout $VERSIONING_BRANCH
          git merge main
