name: Debug

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/debug.yml'
      - 'actions/debug/**'

permissions:
  packages: read
  contents: read

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

env:
  MONO_WORK_DIR: ${{ vars.PRETTIER_CONFIG_DIR }}
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  FORCE_COLOR: 3
  LBIN: /home/runner/.local/bin
  MONO_LOGS_ROOT: /tmp/mono/logs

jobs:
  test:
    name: Debug
    runs-on: ubuntu-latest
    steps:

      - name: GIT
        uses: Duncan3142/mono/actions/git/setup@main

      - name: NPM
        id: npm
        uses: Duncan3142/mono/actions/npm/setup@main
        with:
          cwd: ${{ env.MONO_WORK_DIR }}

      - name: Utils
        uses: Duncan3142/mono/actions/utils/@main
