name: Prettier Config CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: main
    paths:
      - 'pkgs/prettier-config/**'
      - '!pkgs/prettier-config/.gitignore'
      - '!pkgs/prettier-config/.changeset/*'
      - '!pkgs/prettier-config/CHANGELOG.md'

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./actions/setup
        with:
          github-actor: ${{ github.actor }}
      - name: Build
        uses: ./actions/build
