name: Prettier Config CD

on:
  push:
    branches:
      - main
    paths:
     - 'pkgs/prettier-config/**'

permissions:
  packages: write
  pull-requests: write
  contents: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # - name: Setup
      #   uses: ./actions/setup
      #   with:
      #     github-actor: ${{ github.actor }}
      # - name: Build
      #   uses: ./actions/build
      # - name: Changesets
      #   id: changesets
      #   uses: ./actions/changesets
