name: Prettier Config CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: main
    paths:
      - '.github/workflows/npm-prettier-config-ci.yml'
      - 'pkgs/prettier-config/**'
      - '!pkgs/prettier-config/.changeset/*'
      - '!pkgs/prettier-config/CHANGELOG.md'

env:
  MONO_WORK_DIR: ${{ vars.PRETTIER_CONFIG_DIR }}
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
    name: Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:

      - name: Git
        uses: Duncan3142/mono/actions/git/setup@main

      - name: PNPM
        uses: Duncan3142/mono/actions/pnpm/setup@main
        with:
          cwd: ${{ env.MONO_WORK_DIR }}

      - name: Test
        run: |
          pnpm run format
