name: Prettier Config CD

on:
  push:
    branches:
      - main
    paths:
     - '.github/workflows/npm-prettier-config-cd.yml'
     - 'pkgs/prettier-config/**'

permissions:
  packages: write
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ${{ vars.PRETTIER_CONFIG_DIR }}
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSIONING_BRANCH: ${{ vars.CI_BRANCH_PATH }}/${{ vars.SEMVER_BRANCH_PATH }}/${{ vars.PRETTIER_CONFIG_DIR }}


concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  cd:
    name: CD
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:

      - name: Git
        uses: Duncan3142/mono/actions/git/setup@main

      - name: PNPM
        id: pnpm
        uses: Duncan3142/mono/actions/pnpm/setup@main
        with:
          cwd: ${{ env.MONO_WORK_DIR }}

      - name: Changesets
        id: changesets
        uses: Duncan3142/mono/actions/pnpm/changesets@main
        with:
          cwd: ${{ env.MONO_WORK_DIR }}

      - if: steps.changesets.outputs.count != '0'
        name: Version
        id: version
        uses: Duncan3142/mono/actions/version/npm@main
        with:
          semver-branch: ${{ env.VERSIONING_BRANCH }}
          base-branch: ${{ github.ref_name }}
          cwd: ${{ env.MONO_WORK_DIR }}
          pkg-name: ${{ steps.pnpm.outputs.name }}
          gh-token: ${{ secrets.GITHUB_TOKEN }}

      - if: steps.version.outcome == 'skipped'
        name: Publish
        uses: Duncan3142/mono/actions/publish/npm@main
        with:
          cwd: ${{ env.MONO_WORK_DIR }}

      #
