name: Prettier Config CD

on:
  push:
    branches:
      # - main
      - disabled
    paths:
     - '.github/workflows/npm-prettier-config-cd.yml'
     - 'pkgs/prettier-config/**'

permissions:
  packages: write
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ${{ vars.PRETTIER_CONFIG_DIR }}
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSIONING_BRANCH: ${{ vars.CI_BRANCH_PATH }}/${{ vars.SEMVER_BRANCH_PATH }}/${{ vars.PRETTIER_CONFIG_DIR }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  cd:
    name: CD
    runs-on: ubuntu-22.04
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:

      - name: CD
        run: |
          exit 0
