name: Prettier Config CD

on:
  push:
    branches:
      - main
    paths:
     - '.github/workflows/npm-prettier-config-cd.yml'
     - 'pkgs/prettier-config/**'

permissions:
  packages: write
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VERSIONING_BRANCH: ${{ vars.VERSIONING_BRANCH }}
  INITIAL_FETCH_DEPTH: 16

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:

      - name: Git
        uses: Duncan3142/mono/actions/git/setup@main

      - name: PNPM
        uses: Duncan3142/mono/actions/pnpm/setup@main
        with:
          cwd: ${{ env.MONO_WORK_DIR }}

      - name: Changeset Status
        id: changeset-status
        run: |
          mkdir -p .tmp
          pnpm exec changeset status --output="./.tmp/changes_status.json"
          CHANGE_COUNT=$(jq '.changesets | length' ./.tmp/changes_status.json)
          echo Changeset count: "$CHANGE_COUNT"
          echo "count=${CHANGE_COUNT}" >> "$GITHUB_OUTPUT"

      - name: Publish
        if: steps.changeset-status.outputs.count == '0'
        run: |
          echo Running publish...
          # pnpm exec changeset publish
          # git push --follow-tags --no-verify

    outputs:
      requires-versioning: ${{ steps.changeset-status.outputs.count != '0' }}

  version:
    name: Version
    runs-on: ubuntu-latest
    concurrency: ${{ vars.VERSION_CONCURRENCY_GROUP }}
    needs: publish
    if: needs.publish.outputs.requires-versioning == 'true'
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:

      - name: Git
        uses: Duncan3142/mono/actions/git/setup@main
        with:
          fetch-depth: ${{ env.INITIAL_FETCH_DEPTH }}
          ref-specs: '["refs/heads/${{ env.VERSIONING_BRANCH }}:refs/remotes/origin/${{ env.VERSIONING_BRANCH }}"]'

      - name: Checkout Versioning Branch
        id: checkout
        uses: Duncan3142/mono/actions/git/checkout@main
        with:
          name: ${{ env.VERSIONING_BRANCH }}

      - name: Merge base
        id: base
        uses: Duncan3142/mono/actions/git/merge-base@main
        with:
          head-ref: refs/heads/${{ env.VERSIONING_BRANCH }}
          base-ref: ${{ github.ref}}

      - name: PNPM
        uses: Duncan3142/mono/actions/pnpm/setup@main
        with:
          cwd: ${{ env.MONO_WORK_DIR }}

      - name: Version
        id: version
        uses: Duncan3142/mono/actions/pnpm/version@main
        with:
          base: ${{ github.ref }}
          cwd: ${{ env.MONO_WORK_DIR }}

      - name: PR
        if : steps.version.outputs.changes == 'true'
        run: |
          gh pr create --base ${{ github.ref_name }} --title "Version packages" --body "Version packages"
          gh pr merge --auto --squash
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
