name: Prettier Config CI

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: main
    paths:
      - '.github/workflows/npm-prettier-config-ci.yml'
      - 'pkgs/prettier-config/**'
      - '!pkgs/prettier-config/.changeset/*'
      - '!pkgs/prettier-config/CHANGELOG.md'

env:
  MONO_WORK_DIR: ./pkgs/prettier-config
  GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: ${{ github.workflow_ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.event.pull_request.state == 'open' && github.event.pull_request.draft == false
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./actions/setup
      - name: Test
        run: |
          pnpm run format
