name: Prettier Config CD

on:
  push:
    branches:
      - main
    paths:
     - 'pkgs/prettier-config/**'

permissions:
  packages: write
  pull-requests: write
  contents: write

env:
  MONO_WORK_DIR: ./pkgs/prettier-config

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./actions/pnpm/setup
      - name: Changeset Status
        id: changeset-status
        run: |
          mkdir -p .tmp
          pnpm exec changeset status --output="./.tmp/changes_status.json"
          CHANGE_COUNT=$(jq '.changesets | length' ./.tmp/changes_status.json)
          echo Changeset count: "$CHANGE_COUNT"
          echo "count=${CHANGE_COUNT}" >> "$GITHUB_OUTPUT"
      - name: Publish
        if: steps.changeset-status.outputs.count == '0'
        run: |
          echo Running publish...
          # pnpm exec changeset publish
          # git push --follow-tags --no-verify
    outputs:
      requires-versioning: ${{ steps.changeset-status.outputs.count != '0' }}

  version:
    name: Version
    runs-on: ubuntu-latest
    concurrency: ${{ vars.VERSION_CONCURRENCY_GROUP }}
    needs: publish
    if: needs.publish.outputs.requires-versioning == 'true'
    env:
      GH_PACKAGES_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        working-directory: ${{ env.MONO_WORK_DIR }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup
        uses: ./actions/pnpm/setup
      - name: Version
        id: version
        run: |
          echo Running version...
          pnpm exec changeset version
          git status
