name: "Checkout"
description: |
  Checkout a branch

inputs:
  name:
    description: |
      The branch to checkout
        e.g. `feature-branch`
    required: true
  create:
    description: |
      Create the branch if it does not exist locally
    required: false
    default: "false"
  push:
    description: |
      Push a newly created branch to the remote
    required: false
    default: "false"
  remote:
    description: |
      The remote to push a newly created the branch to
    required: false
    default: "origin"

runs:
  using: "composite"
  steps:

    - name: Checkout
      id: checkout
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.name }}
        REMOTE: ${{ inputs.remote }}
        CREATE: ${{ inputs.create }}
        PUSH: ${{ inputs.push }}
      run: |
        . '${{ github.action_path }}/checkout.sh'
        echo "created=${CREATED}" >> $GITHUB_OUTPUT

outputs:
  created:
    description: "'true' if the branch was created, 'false' otherwise"
    value: ${{ steps.checkout.outputs.created }}
