name: "Checkout"
description: |
  Checkout a branch

inputs:
  name:
    description: |
      The branch to checkout
        e.g. `feature-branch`
    required: true
  create:
    description: |
      Create the branch if it does not exist locally
    required: false
    default: "false"
  push:
    description: |
      Push a newly created branch to the remote
    required: false
    default: "false"
  remote:
    description: |
      The remote to push a newly created the branch to
    required: false
    default: "origin"

runs:
  using: "composite"
  steps:

    - name: Checkout
      id: checkout
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.name }}
      run: |
        CREATED=false
        if git checkout "${BRANCH_NAME}"; then
          echo "Ref for ${BRANCH_NAME} existed locally"
        else
          echo "Ref for ${BRANCH_NAME} does not exist locally"
          if [ '${{ inputs.create }}' = 'true' ]; then
            git checkout -b "${BRANCH_NAME}"
            CREATED=true
            if [ '${{ inputs.push }}' = 'true' ]; then
              git push -u '${{ inputs.remote }}' "${BRANCH_NAME}"
            fi
          else
            exit 1
          fi
        fi
        echo "created=${CREATED}" >> $GITHUB_OUTPUT

outputs:
  created:
    description: "'true' if the branch was created, 'false' otherwise"
    value: ${{ steps.checkout.outputs.created }}
